### PR TITLE
Fix for COUNT(*) support

### LINKED ISSUE #40: [BUG] COUNT(*) throws an exception
COUNT(*) is throwing exceptions. This is needed to generate Tableau interactive preview.

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

Fix for COUNT(*) support

### Description

[1] Fixed COUNT(*)

### Related Issue

https://bitquill.atlassian.net/browse/AN-855

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov

### CODE REVIEW

File: sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlAggregateTest.java [hunk 1]
```diff
@@ -68,4 +68,10 @@ public void testAggregateColumnTypeMixedAgg() throws SQLException {
         // validate the metadata type matches return type
         runQueryTestColumnType("select age, count(age) from person group by age");
     }
+
+    @Test
+    public void testCountStar() throws SQLException {
```
Comment (alexey-temnikov) [inline sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlAggregateTest.java:73]: Can we add a unit test (not integration test) to compare that translation to gremlin is correct?

Comment (lyndonbauto) [reply sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlAggregateTest.java:73]: Same comment as other PR. We could do it but it would ultimately be really hacky. The other concern is that since we are still in development, if we update how our traversal is formed, we would break our tests.

I was thinking of overhauling the current structure - currently it outputs a Map-like structure, I was thinking of migrating to a List-like output for performance reasons, but was going to wait and see first

**Review by xiazcy — APPROVED** [review]
