### PR TITLE
Move sql-gremlin errors to resources

### LINKED ISSUE #78: [FEATURE] Add error messages in bundle property for sql-gremlin
SQL-Gremlin has hardcoded errors and exceptions - would be good to properly set this up for localization.

### PR DESCRIPTION
**Pull request by simonz-bq**
### Summary

Move sql-gremlin errors to resources

### Description

Moved all error messages to a bundles file and made them more consistent

### Related Issue

https://bitquill.atlassian.net/browse/AN-831

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov
@kylepbit

### CODE REVIEW

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java [hunk 1]
```diff
@@ -0,0 +1,105 @@
+package org.twilmes.sql.gremlin.adapter.util;
```
Comment (kylepbit) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java:20]: Please add license headers.
Please also add a checkstyle rule that enforces presence of these headers.

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+
+import org.slf4j.Logger;
+
+import java.sql.SQLException;
+import java.util.ResourceBundle;
+
+public enum SqlGremlinError {
```
Comment (kylepbit) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java:31]: Please add JavaDocs.

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+    NO_JOIN_COLUMN,
+    NOT_LOGICAL_FILTER;
+
+    private static final ResourceBundle RESOURCE = ResourceBundle.getBundle("error-messages");
+
+    private static String getMessage(final SqlGremlinError key, final Object... formatArgs) {
+        return String.format(RESOURCE.getString(key.name()), formatArgs);
+    }
+
+    public static SQLException get(final SqlGremlinError key, final Logger logger, final Exception cause,
```
Comment (kylepbit) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java]: All public methods (at least) should have JavaDocs.

Comment (kylepbit) [reply sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java]: Note also that this should probably take a `Throwable` instead of `Exception` as the cause.

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+            exception = new SQLException(message, cause);
+            if (logger != null) {
+                logger.error(message, cause);
+            }
+        }
+
+        return exception;
+    }
+
+     public static SQLException get(final SqlGremlinError key, final Logger logger, final Object... formatArgs) {
```
Comment (kylepbit) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java]: Should probably be called `create` instead of `get`, since `get` implies getting something that already exists.

File: sql-gremlin/src/main/resources/error-messages.properties [hunk 5]
```diff
@@ -0,0 +1,73 @@
+#
+# Copyright <2021> Amazon.com, Inc. or its affiliates. All Rights Reserved.
```
Comment (kylepbit) [inline sql-gremlin/src/main/resources/error-messages.properties]: Should this have a -en suffix? Have you tested this with multiple languages, as usually one of the other reasons for using property bundles is allowing for easy localization.

File: src/main/java/software/aws/neptune/jdbc/utilities/SqlError.java [hunk 6]
```diff
@@ -87,6 +87,7 @@
     READ_ONLY,
     RESULT_FORWARD_ONLY,
     RESULT_SET_CLOSED,
+
```
Comment (kylepbit) [inline src/main/java/software/aws/neptune/jdbc/utilities/SqlError.java]: Is this an accidental change?

File: sql-gremlin/src/main/resources/error-messages.properties (hunk 5 above)
Comment (lyndonbauto) [reply sql-gremlin/src/main/resources/error-messages.properties]: I think kyle is right, we missed that in the JDBC driver but I see it in our Bolt connector. Take a look here https://github.com/Bit-Quill/neptunebolt/tree/develop/src/main/resources @simonz-bq you will see the properties files have _en at the end.

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java (hunk 1 above)
Comment (lyndonbauto) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/util/SqlGremlinError.java:20]: Needs a copyright.

We have a license check but it is only on our jdbc driver, perhaps we should extend it into sql-gremlin...

**Review by lyndonbauto — APPROVED** [review]
# Big Props for this change @simonz-bq
