### PR TITLE
Fix ORDER BY on column that includes empty (null values)

### LINKED ISSUE #118: [BUG] ORDER BY on column that has empty (null) values fails

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

Fix ORDER BY on column that includes empty (null values)

### Related Issue

closes #118

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov
@kylepbit

### CODE REVIEW

File: sql-gremlin/src/main/resources/error-messages_en.properties [hunk 1]
```diff
@@ -77,3 +77,4 @@ OFFSET_NOT_SUPPORTED=Unsupported: OFFSET is not currently supported.
 UNSUPPORTED_LITERAL_EXPRESSION="Unsupported: Raw literal expressions without any tables referenced are now supported at this time."
 CANNOT_JOIN_DIFFERENT_EDGES="Error: Cannot perform JOIN on two edges that are not the same (%s != %s)."
 UNSUPPORTED_OPERAND_TYPE="Unsupported operand type %s, cannot rename column."
+UNRECOGNIZED_TYPE="Error, unrecognized type: '%s'."
```
Comment (simonz-bq) [inline sql-gremlin/src/main/resources/error-messages_en.properties]: Nit: missing newline
```suggestion
UNRECOGNIZED_TYPE="Error, unrecognized type: '%s'."

```

File: sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlIncompleteSelectTest.java [hunk 2]
```diff
@@ -37,43 +39,58 @@ protected DataSet getDataSet() {
     @Test
     public void testProject() throws SQLException {
         runQueryTestResults("select name from person", columns("name"),
-                rows(r("Tom"), r("Patty"), r("Phil"), r("Susan"), r("Juanita"), r("Pavel")));
+                rows(r("Tom"), r("Patty"), r("Phil"), r("Susan"), r("Juanita"), r((Object) null)));
```
Comment (simonz-bq) [inline sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlIncompleteSelectTest.java:42]: Hm, I wonder if we should just not have them included in the result because the select is asking for name specifically so getting someone without a name would be unintuitive behavior.

**Review by simonz-bq — APPROVED** [review]

File: sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlIncompleteSelectTest.java (hunk 2 above)
Comment (lyndonbauto) [reply sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlIncompleteSelectTest.java:42]: It is proper SQL to allow NULL values to come out

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlMetadata.java [hunk 3]
```diff
@@ -262,4 +266,50 @@ public void addOutputType(final String outputName, final String colType) {
...
+        for (final String table : getColumnOutputListMap().keySet()) {
+            gremlinTableBases.add(getGremlinTable(table));
+        }
+        if (aggregateTypeExists(column)) {
+            return getOutputType(column, "string");
+        }
+        String renamedColumn = getRenamedColumn(column);
+        if (!aggregateTypeExists(renamedColumn)) {
+            // Sometimes columns are double renamed.
+            renamedColumn = getRenamedColumn(renamedColumn);
```
Comment (alexey-temnikov) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlMetadata.java:281]: If columns are double renamed, shall it be before the if condition?

Comment (lyndonbauto) [reply sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlMetadata.java:281]: If aggregateTypeExists passes then we already know the output type so no point.
