### PR TITLE
Fix issues with openCypher IAM auth signature

### LINKED ISSUE #199: [BUG] Signature mismatch error with Neptune engine version 1.1.1.0
## Describe the bug
Using engine version 1.1.1.0, openCypher JDBC connectivity fails with the following error:
```
shadow.org.neo4j.driver.exceptions.DatabaseException: "Unexpected server exception 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method.
```

## Steps to Reproduce
1. Rename the attached file to `Main.java` (GitHub doesn't allow uploading of `.java` files)
2. Add `implementation "info.picocli:picocli:4.6.3"` as a dependency in `build.gradle`.
3. Set environment variables described [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-set).
4. Run `Main.java` with the parameters `--host` and `--region`. If you're using SSH tunneling, configure your environment as described [here](https://github.com/aws/amazon-neptune-jdbc-driver/blob/develop/markdown/setup/configuration.md), and include parameters `--ssh-file` and `--ssh-host`.

If being used outside of a BI Tool, fill in:
    1. What version of the JDBC Driver are you using? 1.1.0, but also reproducible with develop branch
    2. What language variant are you using (SPARQL, Gremlin, openCypher, SQL)? openCypher
    3. What database are you connecting to (Amazon Neptune, Neo4J, etc)? Amazon Neptune
    4. What engine version of the database are you using? 1.1.1.0.R6, but also reproducible in R5
    5. What Java version are you using? JDK 8
    6. Please attach a code snippet of the code that is causing the error: Attached
    7. If bug occurred during query execution attach the SQL: Refer to the attached file
    8. Attach debug logs if applicable/possible (please ensure it doesn't contain any sensitive information)
    
```
    > Task :Main.main()
22/09/28 19:19:10 [main] INFO test.Main: Connection created
22/09/28 19:19:10 [main] INFO test.Main: Statement created
22/09/28 19:19:10 [main] INFO opencypher.OpenCypherQueryExecutor: Creating driver with encryption.
22/09/28 19:19:10 [main] INFO opencypher.OpenCypherQueryExecutor: Creating driver with IAMSigV4 authentication.
Sep 28, 2022 7:19:10 PM org.neo4j.driver.internal.logging.JULogger info
INFO: Direct driver instance 2123533871 created for server address <neptune cluster endpoint>:65345
Sep 28, 2022 7:19:11 PM org.neo4j.driver.internal.logging.JULogger warn
WARNING: [0x679e263f][<neptune cluster endpoint>:65345][] Fatal error occurred in the pipeline
org.neo4j.driver.exceptions.DatabaseException: "Unexpected server exception 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.'"
	at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:84)
	at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:105)
	at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.unpackFailureMessage(MessageReaderV1.java:83)
	at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:59)
	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
	at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

## Expected behavior
Should be able to execute query without exception.

## Screenshots
N/A

## Environment
Please add the following information to your report:
- OS: [e.g. macOS Big Sur]: Irrelevant
- Version [e.g. 11.6.1]: openjdk version "1.8.0_322"

## Additional Context
The code attached used to work with Neptune engine version 1.0.5.1, but doesn't work after upgrading to 1.1.1.0.
Release notes: https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases-1.1.1.0.html

## Attachment
[Main.txt](https://github.com/aws/amazon-neptune-jdbc-driver/files/9670385/Main.txt)

### PR DESCRIPTION
**Pull request by asarkar**
### Summary

Fix issues with openCypher IAM auth signature.

### Description

1. Update auth token generation to match what is expected by the server in engine release 1.1.1.0. 
2. Add `X-Amz-Security-Token` to support session token.
3. Add unit tests to verify the auth token.

Elaborating on item 1 above:
1. The credentials no longer include `HttpVersion":"HTTP/1.1"`
2. Host: *Before:* `"Host":"bolt://somehost:1234"` *After:* `"Host":"somehost.com:1234"`
    Specifically, we no longer include the protocol in the `Host` header.

### Related Issue

https://github.com/aws/amazon-neptune-jdbc-driver/issues/199
https://github.com/aws/amazon-neptune-jdbc-driver/issues/200

### Additional Reviewers
@beebs-systap

### CODE REVIEW

File: src/test/java/software/aws/neptune/opencypher/OpenCypherIAMRequestGeneratorTest.java [hunk 1]
```diff
@@ -0,0 +1,157 @@
...
+    }
+
+    @Test
+    public void testCreateAuthTokenWithTempCreds() {
+        System.setProperty("aws.sessionToken", DUMMY_SESSION_TOKEN);
+        verifyAuthToken(true);
+    }
+
+    private void verifyAuthToken(final boolean useTempCreds) {
+        final String url = "bolt://somehost.com:58763";
```
Comment (upadhyay-prashant) [inline src/test/java/software/aws/neptune/opencypher/OpenCypherIAMRequestGeneratorTest.java:93]: Is the default protcol `bolt` only ? I remember we had something like bolt+ssl ?

Comment (asarkar) [reply src/test/java/software/aws/neptune/opencypher/OpenCypherIAMRequestGeneratorTest.java:93]: It doesn't matter for the signature. The unit test works regardless of the protocol. It might matter for connectivity, but that's not in the scope of this PR and not changed.

File: src/main/java/software/aws/neptune/opencypher/OpenCypherIAMRequestGenerator.java [hunk 2]
```diff
@@ -48,28 +51,30 @@ public class OpenCypherIAMRequestGenerator {
...
-                    SqlState.CONNECTION_EXCEPTION,
-                    SqlError.FAILED_TO_OBTAIN_AUTH_TOKEN, e);
-        }
+    public static AuthToken createAuthToken(final String url, final String region) {
+        final Request<Void> request = new DefaultRequest<>(SERVICE_NAME);
+        request.setHttpMethod(HttpMethodName.GET);
+        request.setEndpoint(URI.create(url));
+        // Comment out the following line if you're using an engine version older than 1.2.0.0
+        // request.setResourcePath("/opencypher");
+
```
Comment (lyndonbauto) [inline src/main/java/software/aws/neptune/opencypher/OpenCypherIAMRequestGenerator.java:61]: Rather than forcing a user to comment out and recompile, should we perhaps allow them to pass in a flag if they are using an older engine version?

Comment (asarkar) [reply src/main/java/software/aws/neptune/opencypher/OpenCypherIAMRequestGenerator.java:61]: The comment is for me, not for the user. I'll make another PR as soon as this one is merged, in which I'll uncomment the line above. The README will be updated to show which version of the library is compatible with which Neptune engine version.

**Review by upadhyay-prashant — APPROVED** [review]
LGTM

**Review by alexey-temnikov — APPROVED** [review]
