### PR TITLE
ORDER BY using a label fix

### LINKED ISSUE #30: [BUG] ORDER using a label fails
## Describe the bug
ORDER using a label fails

- [x] **Have you validated that this is not currently reported in
    [SQL Support and Limitations](https://github.com/aws/amazon-neptune-jdbc-driver/blob/develop/sql-gremlin/README.asciidoc#sql-support-and-limitations)?**

## Steps to Reproduce
Attempt to run a query that uses a label in an ORDER BY expression.

## Expected behavior
`SELECT column AS label FROM table ORDER BY label` would sort by the label.

## Environment
Any system

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

ORDER BY using a label fix

### Description

[1] Fixes for ORDER BY using a label.

### Related Issue

https://bitquill.atlassian.net/browse/AN-777

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov

### CODE REVIEW

File: sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlAdvancedSelectTest.java [hunk 1]
```diff
@@ -41,6 +41,32 @@ public void testProject() throws SQLException {
                 rows(r("Tom"), r("Patty"), r("Phil"), r("Susan"), r("Juanita"), r("Pavel")));
     }
 
+    @Test
+    public void testOrder() throws SQLException {
```
Comment (alexey-temnikov) [inline sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlAdvancedSelectTest.java:45]: Can we add a unit test (not integration test) to compare that translation to gremlin is correct?

Comment (lyndonbauto) [reply sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlAdvancedSelectTest.java:45]: With the current setup, it's technically possible.... We need to send in SQL to get our syntax tree out, and the Gremlin that comes out is actually a GraphTraversal Object and is a pretty complex traversal, doing it would ultimately be a really hacky setup.

**Review by xiazcy — APPROVED** [review]
