### PR TITLE
Fix for false positive exception on statement shutdown

### LINKED ISSUE #108: [BUG] False positive exception on statement close
## Describe the bug
Close invokes cancelQuery which dumps out a false positive exception.

2021-12-14 14:07:54.417 FINE   296 [pool-4-thread-15 - s.flush] java.sql.SQLException: Cannot cancel query, it is either completed or has not started.
        at software.aws.neptune.jdbc.utilities.SqlError.createSQLException(SqlError.java:154)
        at software.aws.neptune.jdbc.utilities.QueryExecutor.cancelQuery(QueryExecutor.java:223)
        at software.aws.neptune.jdbc.Statement.close(Statement.java:91)
        at jdk.internal.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.onseven.dbvis.jdbc.b.c.b(Z:3273)
        at com.onseven.dbvis.jdbc.b.g$_b.call(Z:3572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
SQLException: SQLState(HY008)

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

Fix for false positive exception on shutdown

### Description

Query executor spits out an exception log when statement is closed. This is because it doesn't realize that close is just doing a final check to cancel any pending queries. This fixes that false positive exception.
[1] Fixed false positive issue for query executor

### Related Issue

closes #108 

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov
@kylepbit

### CODE REVIEW

File: src/main/java/software/aws/neptune/jdbc/utilities/QueryExecutor.java [hunk 1]
```diff
@@ -217,9 +211,12 @@ private void resetQueryState() {
      *
      * @throws SQLException if query cancellation fails.
      */
-    public void cancelQuery() throws SQLException {
+    public void cancelQuery(final boolean isClosing) throws SQLException {
         synchronized (lock) {
             if (queryState.equals(QueryState.NOT_STARTED)) {
+                if (isClosing) {
+                    return;
+                }
```
Comment (simonz-bq) [inline src/main/java/software/aws/neptune/jdbc/utilities/QueryExecutor.java:219]: This part confuses me a bit but I could be lacking context.

If we're closing, then we only do nothing if the state is NOT_STARTED. What about CANCELLED, since we wouldn't care about an exception on closing? 

I'm not saying this is wrong, but it feels kind of convoluted and I want to double check that all checked paths are correct.

**Review by simonz-bq — APPROVED** [review]

File: src/main/java/software/aws/neptune/jdbc/utilities/QueryExecutor.java (hunk 1 above)
Comment (lyndonbauto) [reply src/main/java/software/aws/neptune/jdbc/utilities/QueryExecutor.java:219]: We care about logging an exception on closing, but not if it wasn't starting.
