### PR TITLE
Fixing Tableau Extract Error

### LINKED ISSUE #56: [BUG] Tableau 2021.3 Extract feature does not work
## Describe the bug
Tableau 2021.3 Extract feature does not work and reports an error with tinkerpop connection pool shutdown.

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

Fixing Tableau Extract Error

### Description

[1] Fixed some logic around connection pooling.
[2] As discussed with Alexey, this is non-trivial to test and we will brainstorm a way to test this on Monday after GA release. For now we will rely on manual testing done by Yang, Alexey and Lyndon using Tableau.

> Connection pool within TinkerPop was the connection pool that was throwing an exception.
> SqlGremlinQueryExecutor held a static SqlConverter, which was given a GraphTraversalSource upon instantiation. This was then used to run Traversals as they came.
> Close function would then close that GraphTraversalSource on the SqlGremlinQueryExecutor, so next query comes along and TinkerPop (library that implements GraphTraversalSource) would throw an exception saying that their connection pool is shutdown.
> Close still closes the GraphTraversalSource (because it should), but now each query gets a fresh GraphTraversalSource to work off of, and it is regenerated if it is closed, then invoked again 

### Related Issue

https://bitquill.atlassian.net/browse/AN-879

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov
@kylepbit

### CODE REVIEW

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/results/pagination/Pagination.java [hunk 1]
```diff
@@ -60,7 +60,9 @@ public void run() {
             }
             // If we run out of traversal data (or hit our limit), stop and signal to the result that it is done.
             sqlGremlinQueryResult.assertIsEmpty();
+            closeTraversal();
         } catch (final Exception e) {
+            closeTraversal();
```
Comment (simonz-bq) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/results/pagination/Pagination.java]: Use finally instead?

Comment (lyndonbauto) [reply sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/results/pagination/Pagination.java]: Good idea.

**Review by xiazcy — APPROVED** [review]
