### PR TITLE
Fix for Miscellaneous Query Issues from Bug Bash

### LINKED ISSUE #41: [BUG] SELECT query issues in DBVisualizer
The following SELECT queries were reported to have produced issues in DBVisualizer and need to be investigated further:

- SELECT COUNT(code), COUNT(code) FROM country errors
- SELECT COUNT(code), COUNT(*) FROM country errors
- select country, count(country), count(1) from "gremlin"."airport" group by country
- select country, count(city), sum(lon), avg(lon), min(lon), max(lon) from "gremlin"."airport" group by country
- select country from "gremlin"."airport" order by 1
- select distinct country from "gremlin"."airport" order by country desc
- select country from "gremlin"."airport" order by country asc nulls first
- select sum(lon) from "gremlin"."airport" where country = 'test'

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

Fix for Miscellaneous Query Issues from Bug Bash

### Description

- Added support for ordinal based ORDER BY
- Fixed COUNT(<literal>) support
- Fixed bug with SELECT <aggregate> FROM <table> WHERE <predicate that will return no results>

### Related Issue

https://bitquill.atlassian.net/browse/AN-866

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov
@kylepbit

### CODE REVIEW

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/ast/nodes/select/GremlinSqlSelectSingle.java [hunk 1]
```diff
@@ -233,6 +242,23 @@ private void appendByGraphTraversal(final GremlinSqlNode gremlinSqlNode, final S
...
+                            graphTraversal);
+                } else {
+                    throw new SQLException("Error, ordinal value of ORDER BY must be between 1 and the number of columns (inclusive).");
+                }
+            } else {
+                throw new SQLException("Error, invalid ORDER BY column literal.");
+            }
+        } else {
+            throw new SQLException(
+                    String.format("Error, could not apply ORDER BY to {}.", gremlinSqlNode.getClass().getName()));
```
Comment (alexey-temnikov) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/ast/nodes/select/GremlinSqlSelectSingle.java]: Do we have options to elaborate on the error message? In other words is it something that user did wrong and should fix, or possibly an unsupported feature. If it is the last scenario - we should indicate user can check out the page with the list of limitations and supported features.

**Review by kylepbit — COMMENTED** [review]
I think you've fixed 3 distinct cases, but there is only one additional test case. We should have at least 3 test cases added here, likely many more, to cover off the cases that have been fixed.

**Review by xiazcy — APPROVED** [review]

**Comment by lyndonbauto** [comment]
@kylepbit 
> I think you've fixed 3 distinct cases, but there is only one additional test case. We should have at least 3 test cases added here, likely many more, to cover off the cases that have been fixed.

Agreed - I will be adding many tests over time, I was just focusing on these specific issues in this ticket.
