### PR TITLE
Fixed HAVING support and did some rearchitecting to simplify any future additions to this part of the code

### LINKED ISSUE #32: [BUG] HAVING does not work properly
## Describe the bug
HAVING does not work properly

- [x] **Have you validated that this is not currently reported in
    [SQL Support and Limitations](https://github.com/aws/amazon-neptune-jdbc-driver/blob/develop/sql-gremlin/README.asciidoc#sql-support-and-limitations)?**

## Steps to Reproduce
Attempt to run a query that uses HAVING.

## Expected behavior
`SELECT COUNT(column) FROM table GROUP BY column HAVING COUNT(column) > value` should work.

## Environment
Any

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

Fixed HAVING support and did some rearchitecting to simplify any future additions to this part of the code

### Description

[1] Did some rearchitecture of the WHERE and HAVING traversal generation
[2] Added HAVING test cases
[3] Tried to remove code to common places

### Related Issue

https://bitquill.atlassian.net/browse/AN-854

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov

### CODE REVIEW

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlMetadata.java [hunk 1]
```diff
@@ -231,7 +242,11 @@ public String getActualTableName(final String table) throws SQLException {
     }
 
     public void checkAggregate(final SqlNodeList sqlNodeList) {
-        isAggregate = sqlNodeList.getList().stream().allMatch(SqlMetadata::isAggregate);
+        isAggregate = sqlNodeList.getList().stream().anyMatch(SqlMetadata::isAggregate);
+    }
+
+    public void checkGroup(final SqlNode sqlNode) {
```
Comment (simonz-bq) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlMetadata.java]: Nit: naming of this function is nebulous

**Review by simonz-bq — APPROVED** [review]
