### PR TITLE
Fixed exception in DBVisualizer for LIMIT 1 queries.

### LINKED ISSUE #69: [BUG] LIMIT 1 DBVisualizer Exception
## Describe the bug
SOmetimes LIMIT 1 throws exceptions in dbvisualizer. THis looks like a java thread interrupt is getting pushed into the thread dbvisualizer is monitoring the ResultSet with.

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

Fixed exception in DBVisualizer for LIMIT 1 queries.

### Description

Limit 1 was giving intermittent exceptions in DBVisualizer. I investigated this for a while and found the root cause. Due to some timing with LIMIT 1, the interrupt (intended to unblock our BlockingQueue) was interrupting the ResultSet retrieval thread of DBVisualizer.

DBVisualizer was then reporting an error, even though all the results were properly retrieved.

To fix this I did changed the BlockingQueue unblock mechanism to use a specified extension of the List<Object> interface I made, which denotes that there are no more results. This removes the need for try/catch logic, synchronized blocks, over overall reduces complexity of pagination.

LIMIT 1 no longer errors in DBVisualizer, and I added some extra tests for it in our test class.

### Related Issue

closes #69 

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov
@kylepbit

### CODE REVIEW

File: src/main/java/software/aws/neptune/gremlin/sql/SqlGremlinResultSet.java [hunk 1]
```diff
@@ -79,15 +78,9 @@ protected void doClose() throws SQLException {
     @Override
     public boolean next() throws SQLException {
         final Object res;
```
Comment (lyndonbauto) [inline src/main/java/software/aws/neptune/gremlin/sql/SqlGremlinResultSet.java:80]: INline assignment

File: sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlBaseTest.java [hunk 2]
```diff
@@ -151,20 +151,12 @@ public void assertColumns(final List<String> actual, final List<String> expected
...
-                    }
-                }
-                if (res instanceof List<?>) {
-                    this.rows.add((List<?>) res);
+                final List<?> res = sqlGremlinQueryResult.getResult();
+                if (res instanceof SqlGremlinQueryResult.EmptyResult) {
+                    break;
                 }
+                this.rows.add(res);
             } while (true);
```
Comment (simonz-bq) [inline sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlBaseTest.java]: Nit: wouldn't this be better as a `while NOT res instanceof EmptyResult` instead of a do while true?

**Review by simonz-bq — APPROVED** [review]

File: sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlBaseTest.java (hunk 2 above)
Comment (lyndonbauto) [reply sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlBaseTest.java]: @simonz-bq Lol, how did I miss this 🙃  will fix that. Thanks
