### PR TITLE
Fixed aggregate issue and added unsupported exception for WHERE in JOIN

### LINKED ISSUE #126: [BUG] Aggregates have issue with null values when used in conjunction with filters

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

Fixed aggregate issue and added unsupported exception for WHERE in JOIN

### Description

Fixed aggregate issue and added unsupported exception for WHERE in JOIN
closes #126 

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov
@kylepbit

### CODE REVIEW

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlMetadata.java [hunk 1]
```diff
@@ -218,8 +217,15 @@ public String getRenameFromActual(final String actual) {
     }
 
     public String getActualColumnName(final GremlinTableBase table, final String column) throws SQLException {
-        final String actualColumnName = getRenamedColumn(column);
-        return table.getColumn(actualColumnName).getName();
+        if (table.hasColumn(column)) {
+            return table.getColumn(column).getName();
+        }
+        if (columnRenameMap.containsKey(column)) {
```
Comment (lyndonbauto) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlMetadata.java]:
```suggestion
        } else if (columnRenameMap.containsKey(column)) {
```

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java [hunk 2]
```diff
@@ -100,9 +99,20 @@ public static void addProjection(final List<GremlinSqlIdentifier> gremlinSqlIden
...
-                                      final GraphTraversal<?, ?> subGraphTraversal) {
-        graphTraversal.by(subGraphTraversal);
+    public static void applyTraversal(boolean apply,
+                                      final GraphTraversal graphTraversal,
+                                      final GraphTraversal subGraphTraversal) {
+        if (apply) {
+            graphTraversal.by(__.coalesce(subGraphTraversal, __.constant(SqlGremlinQueryResult.NULL_VALUE)));
+        } else {
+            graphTraversal.by(subGraphTraversal);
+        }
```
Comment (lyndonbauto) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java]:
```suggestion
            graphTraversal.by((apply ? __.coalesce(subGraphTraversal, __.constant(SqlGremlinQueryResult.NULL_VALUE)) : subGraphTraversal));
```

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java [hunk 3]
```diff
@@ -100,9 +99,20 @@ public static void addProjection(final List<GremlinSqlIdentifier> gremlinSqlIden
     }
 
 
-    public static void applyTraversal(final GraphTraversal<?, ?> graphTraversal,
-                                      final GraphTraversal<?, ?> subGraphTraversal) {
-        graphTraversal.by(subGraphTraversal);
+    public static void applyTraversal(boolean apply,
```
Comment (xiazcy) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java]:
```suggestion
    public static void applyTraversal(final boolean apply,
```

**Review by xiazcy — APPROVED** [review]
Minor changes.

File: sql-gremlin/README.asciidoc [hunk 4]
```diff
@@ -45,6 +45,8 @@ Identifier matching is case-sensitive and identifiers that match a reserved SQL
 === Joins
 Currently, the driver only support `INNER JOIN` on two vertices that are connected by an edge. When looking at vertices you will see `<edge_label>_IN_ID` or `<edge_label>_OUT_ID`.
 
+`WHERE` and `HAVING` are not currently supported in conjunction with a `JOIN` clause.
+
```
Comment (alexey-temnikov) [inline sql-gremlin/README.asciidoc:50]: Should we also add that we do not currently generate FKs?

```suggestion
Foreign keys are not generated and not exposed in JDBC metadata at this time.

```

File: sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlAdvancedSelectTest.java [hunk 5]
```diff
@@ -147,7 +147,7 @@ public void testWhere() throws SQLException {
                 rows(r("Tom", 35), r("Juanita", 50)));
     }
 
-    // TODO: Support NOT on operators
+    // TODO: Support where NOT on operators
```
Comment (alexey-temnikov) [inline sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlAdvancedSelectTest.java]: Shall we remove TODO, since all Disabled tests are actually a todo. The additional comment might be unnecessary?
```suggestion
    // TODO #127: Support NOT in WHERE filter.
```

**Review by alexey-temnikov — APPROVED** [review]

File: sql-gremlin/README.asciidoc [hunk 6]
```diff
@@ -66,11 +68,13 @@ Supported operators are listed below. Arithmetic, string, conditional and date o
...
 ==== Comparison Operators
 * `value1 <op> value2` where `op` is one of : `=`, `<>`, `<`, `>`, `<=` or `>=`
+* `NOT` in conjunction with a comparison operator is not currently supported
 
 ==== Logical Operators
 * `boolean1` OR `boolean2`
 * `boolean1` AND `boolean2`
-* NOT `boolean2`
+* NOT `boolean2` is supported only when used with a boolean valued column in `WHERE`/`HAVING` filters
+* NOT `boolean2` is supported with expressions and boolean values in `SELECT` clause
```
Comment (simonz-bq) [inline sql-gremlin/README.asciidoc:78]: I don't think we should be calling it `boolean2` here.

I also think this wording can be improved to be more clear that we're talking about expressions and column type values but this is a NIT.

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java [hunk 7]
```diff
@@ -100,9 +99,20 @@ public static void addProjection(final List<GremlinSqlIdentifier> gremlinSqlIden
...
+            graphTraversal.by(__.coalesce(subGraphTraversal, __.constant(SqlGremlinQueryResult.NULL_VALUE)));
+        } else {
+            graphTraversal.by(subGraphTraversal);
+        }
+    }
+
+
+    public static void applyTraversal(final GraphTraversal graphTraversal,
+                                      final GraphTraversal subGraphTraversal) {
+        applyTraversal(false, graphTraversal, subGraphTraversal);
```
Comment (simonz-bq) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java]: Nit: Standard Java practices usually have overloaded methods with the missing parameter at the end. `apply` should be last here.
```suggestion
        applyTraversal(graphTraversal, subGraphTraversal, false);
```

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java [hunk 8]
```diff
@@ -151,7 +163,8 @@ private static void appendGraphTraversal(final String table, final String column
             }
         } else {
             // It's this vertex/edge.
-            if (columnName.toLowerCase(Locale.getDefault()).startsWith(gremlinTableBase.getLabel().toLowerCase(Locale.getDefault()))) {
+            if (columnName.toLowerCase(Locale.getDefault())
+                    .startsWith(gremlinTableBase.getLabel().toLowerCase(Locale.getDefault()))) {
```
Comment (simonz-bq) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java:163]: Locale.getDefault() here is redundant. No need for it.

Comment (lyndonbauto) [reply sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java:163]: This was forced from a checkstyle.

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java [hunk 9]
```diff
@@ -100,9 +99,16 @@ public static void addProjection(final List<GremlinSqlIdentifier> gremlinSqlIden
     }
 
 
-    public static void applyTraversal(final GraphTraversal<?, ?> graphTraversal,
-                                      final GraphTraversal<?, ?> subGraphTraversal) {
-        graphTraversal.by(subGraphTraversal);
+    public static void applyTraversal(final boolean apply,
+                                      final GraphTraversal graphTraversal,
+                                      final GraphTraversal subGraphTraversal) {
```
Comment (lyndonbauto) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/SqlTraversalEngine.java]:
```suggestion
    public static void applyTraversal(GraphTraversal graphTraversal,
                                      final GraphTraversal subGraphTraversal,
                                      final boolean apply) {
```

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/ast/nodes/select/GremlinSqlSelect.java [hunk 10]
```diff
@@ -130,12 +130,12 @@ protected void applyColumnRetrieval(final GraphTraversal<?, ?> graphTraversal, f
                         SqlTraversalEngine.getEmptyTraversal(stepDirection, sqlMetadata);
                 SqlTraversalEngine
                         .applySqlIdentifier((GremlinSqlIdentifier) gremlinSqlNode, sqlMetadata, subSubGraphTraversal);
-                SqlTraversalEngine.applyTraversal(subGraphTraversal, subSubGraphTraversal);
+                SqlTraversalEngine.applyTraversal(true, subGraphTraversal, subSubGraphTraversal);
```
Comment (lyndonbauto) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/ast/nodes/select/GremlinSqlSelect.java]:
```suggestion
                SqlTraversalEngine.applyTraversal(subGraphTraversal, subSubGraphTraversal, true);
```

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/ast/nodes/select/GremlinSqlSelect.java [hunk 11]
```diff
@@ -130,12 +130,12 @@ protected void applyColumnRetrieval(final GraphTraversal<?, ?> graphTraversal, f
...
             } else if (gremlinSqlNode instanceof GremlinSqlBasicCall) {
                 final GraphTraversal<?, ?> subSubGraphTraversal =
                         SqlTraversalEngine.getEmptyTraversal(stepDirection, sqlMetadata);
                 ((GremlinSqlBasicCall) gremlinSqlNode).generateTraversal(subSubGraphTraversal);
-                SqlTraversalEngine.applyTraversal(subGraphTraversal, subSubGraphTraversal);
+                SqlTraversalEngine.applyTraversal(true, subGraphTraversal, subSubGraphTraversal);
```
Comment (lyndonbauto) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/ast/nodes/select/GremlinSqlSelect.java]:
```suggestion
                SqlTraversalEngine.applyTraversal(subGraphTraversal, subSubGraphTraversal, true);
```

**Review by simonz-bq — APPROVED** [review]
