### PR TITLE
Fixed JOIN query bug when operating on vertices of different labels

### LINKED ISSUE #80: [BUG] JOIN query potential bug
The following was reported and needs investigation:

Tried to use Tableau to join continent and airport on contains_OUT/IN. Got weird message: Unexpected Errorjava.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: {"detailedMessage":"Invalid string=","requestId":"6c1da1df-bef7-421f-81bb-2de123a8ddfe","code":"InvalidParameterException"}java.io.PrintWriter@4fafe9a3Error Code: FAB9A2C5

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

Fixed JOIN query bug when operating on vertices of different labels

### Description

- Resolved issue with JOIN operation on vertices that are of different labels
- Issue was the no results were coming out when labels were different, looking at the editted SqlMetadata function, the incorrect logic is visible 
- Added tests for JOIN on vertices of same and different labels
- Added tests for JOIN with GROUP BY

### Related Issue

closes #80 

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov
@kylepbit

### CODE REVIEW

File: sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlJoinTest.java [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+                columns("name"),
+                rows(r("Tom"), r("Patty"), r("Phil"), r("Susan"), r("Juanita"), r("Pavel")));
+
+        runJoinQueryTestResults("SELECT spaceship.model FROM gremlin.person person " +
+                        "INNER JOIN gremlin.spaceship spaceship ON (person.pilots_OUT_ID = spaceship.pilots_IN_ID) " +
+                        "GROUP BY spaceship.model",
+                columns("model"),
+                rows(r("delta 1"), r("delta 2"), r("delta 3")));
+    }
+
```
Comment (simonz-bq) [inline sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlJoinTest.java]: Nit: Whitespace
```suggestion
```

**Review by simonz-bq — APPROVED** [review]
