### PR TITLE
AN-915 fix CAST null pointer exception

### LINKED ISSUE #91: [BUG] Null pointer exception when using CAST

### PR DESCRIPTION
**Pull request by lyndonbauto**
### Summary

Fixed null pointer exception in CAST statement

### Description

Added check for specific condition that had NPE

### Related Issue

closes #91

### Additional Reviewers
@birschick-bq
@lyndonb-bq
@xiazcy
@simonz-bq
@alexey-temnikov
@kylepbit

### CODE REVIEW

File: sql-gremlin/src/main/resources/error-messages_en.properties [hunk 1]
```diff
@@ -73,4 +73,5 @@ WHERE_BASIC_LITERALS=Unsupported: Unsupported WHERE clause - Only basic literal
 UNEXPECTED_JOIN_NODES=Error: Expected nodes in join comparison to be GremlinSqlIdentifiers.
 NO_JOIN_COLUMN=Error: Expected to find join column for renamed table.
 NOT_LOGICAL_FILTER=Error: Cannot convert %s to %s.
-OFFSET_NOT_SUPPORTED=Unsupported: OFFSET is not currently supported.
\ No newline at end of file
+OFFSET_NOT_SUPPORTED=Unsupported: OFFSET is not currently supported.
+UNSUPPORTED_LITERAL_EXPRESSION="Error: Raw literal expressions without any tables referenced are now supported at this time."
```
Comment (simonz-bq) [inline sql-gremlin/src/main/resources/error-messages_en.properties]: Should be prefixed with Unsupported instead of Error.

File: sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/ast/nodes/GremlinSqlFactory.java [hunk 2]
```diff
@@ -137,7 +137,9 @@ public static GremlinSqlNode createNode(final SqlNode sqlNode) throws SQLExcepti
 
     public static GremlinSqlSelect createSelect(final SqlSelect selectRoot, final GraphTraversalSource g)
             throws SQLException {
-        if (selectRoot.getFrom() instanceof SqlJoin) {
+        if (selectRoot.getFrom() == null) {
+            throw SqlGremlinError.create(SqlGremlinError.UNSUPPORTED_LITERAL_EXPRESSION);
```
Comment (simonz-bq) [inline sql-gremlin/src/main/java/org/twilmes/sql/gremlin/adapter/converter/ast/nodes/GremlinSqlFactory.java]: This should probably be `createNotSupported`

File: sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlNotSupportedTest.java [hunk 3]
```diff
@@ -49,9 +48,9 @@ public void testSubQuery() throws SQLException {
                 SqlGremlinError.UNKNOWN_OPERATOR, "SCALAR_QUERY");
     }
 
-    // TODO: Handle CAST
-    @Disabled
+    @Test
     public void testCast() throws SQLException {
-        runNotSupportedQueryTestThrows("SELECT CAST(17 AS varchar)", null);
+        runQueryTestThrows("SELECT CAST(17 AS varchar)", SqlGremlinError.UNSUPPORTED_LITERAL_EXPRESSION);
+        runQueryTestThrows("SELECT CAST(person.age as CHAR) FROM person", SqlGremlinError.UNKNOWN_OPERATOR, "CAST");
```
Comment (simonz-bq) [inline sql-gremlin/src/test/java/org/twilmes/sql/gremlin/adapter/GremlinSqlNotSupportedTest.java]: This test will need to be updated to account for the SqlNotSupportedError instead.

**Review by simonz-bq — CHANGES_REQUESTED** [review]

**Review by simonz-bq — APPROVED** [review]
